### ISSUE TITLE
more than one simultaneous download problem

### ISSUE THREAD

**Issue by duck7000** [tsuliwaensis/AlwaysClear#1]
Hi there

First of all a big thank you for updating this very useful extension.

But i have a slight problem.
It works perfectly when there is only one download, but when there are multiple downloads the download bar disappears when one of them is finished. The other downloads are still being downloaded but not visible anymore other than go to the download tab.

It should, like the old version did, only hide the download bar when all downloads are finished.

I'm using the extension on Chromium 68.0.3440.106 on Linuxmint 18

**Comment by tfabris** [comment]
I believe it's these lines in the code that cause the issue:
```
		chrome.downloads.setShelfEnabled(false);
		chrome.downloads.setShelfEnabled(true);
```

Is setting/clearing the [shelf](https://developer.chrome.com/extensions/downloads#method-setShelfEnabled) needed in this program? I haven't tried making changes to these lines, but my expectation is that Chrome should handle clearing the shelf itself. In other words, if these two lines were removed, then the behavior would be as expected: that the shelf would only disappear when the last download completed.

I can only imagine that these lines got added for a reason. Perhaps something about the most recent code causes the shelf to unexpectedly hang around, and these lines needed to be added? Not sure.

My suggestion:
- Try removing the lines and see if everything works OK.
- If not, see if the code can query whether or not any active downloads remain, and only clear the shelf if there are no more active downloads.

**Comment by duck7000** [comment]
@tfabris 

Thank you for your response!

I forgot all about this issue, i posted this august last year..

Well your solution to remove the 2 lines actually works!
Chromium clears the download bar only if all downloads are finished.

Thanks for this solution!
Although it would have been nice if the maintainer of this github has responded to this issue, i'm glad you did!

**Comment by tfabris** [comment]
Cool! Here's the beauty of GitHub and open source: You could submit your change as a pull request, then @tsuliwaensis could review the change and potentially include it in the next release.

**Comment by duck7000** [comment]
you are absolutely right, open source is great!

Pull Request is made, lets hope that the maintainer include it in the next release.

Thanks again!

**Comment by tsuliwaensis** [comment]
I merged the request and updated the extension to version 2.1.4. 

@duck7000  Thank you! 🙏 🙌
