### ISSUE TITLE
Thanks for doing this! Does it still have the bug of resetting the downloads folder?

### ISSUE THREAD

**Issue by tfabris** [tsuliwaensis/AlwaysClear#2]
I'm the author of the original "always clear downloads" extension. I kept meaning to update it so that it would work with the new Google API requirements. I never got around to it. Thanks so much for taking my original extension and updating it to work with the new API requirements, and for making it open source on GitHub.

Question: Does it still have the bug where it resets the downloads folder to the Chrome default all the time? My original version of the extension had this bug, and it was Chrome's API bug, not mine. They closed the bug without fixing it. Details here: https://bugs.chromium.org/p/chromium/issues/detail?id=158965

**Comment by tfabris** [comment]
Yeah, that bug is still there. No worries, it's not your bug! Keep it in mind, though, since some of your users will complain about it (mine did).

**Comment by tsuliwaensis** [comment]
@tfabris It was my pleasure to update the extension. It's unfortunate Google never added the functionality into Chrome. (Sorry it took me so long to respond).
